### ISSUE TITLE
for Jscholarship deposit, submitter is being sent as "author"

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/nihms-submission#114] opened 2018-06-19 19:55 UTC
as shown in the below screenshot, Peter A Campochiaro is actually the submitter of this deposit. 

the Author information, if available is stored in the submission object's metadata blob, will need to be parsed out from there. 

![screen shot 2018-06-19 at 3 17 27 pm](https://user-images.githubusercontent.com/11050142/41620864-f6547c0c-73d8-11e8-8a90-62f336e8ca4a.png)

**Comment by emetsger** [comment] 2018-06-20 13:49
@Trumbore I think the issue is that not only is `Campochiaro` the submitter (not an author), the other authors are not in the metadata at all.

**Comment by emetsger** [comment] 2018-06-25 00:35
Fixed in #116.

**Closed by emetsger** 2018-06-25 00:35 UTC
Labels: blocker, bug
